apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  namespace: model-deployments
spec:
  selector:
    app: python-api
  ports:
    - protocol: TCP
      port: 80 # The port exposed outside the cluster
      targetPort: 8000 # The port used by the Python app inside the container
      nodePort: 30007 # You can specify a custom NodePort or let Kubernetes choose one
  type: NodePort
