apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read/write from the volume
  hostPath:
    path: "/mnt/shared"  # This path depends on the environment (e.g., local path or cloud storage)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: model-deployments  # Specify the namespace explicitly here
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
