apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: model-deployments
  name: deployment-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "update", "delete"]
  - apiGroups: [""]  # Core API group
    resources: ["namespaces", "services", "pods", "pods/log"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [ "autoscaling" ]
    resources: [ "horizontalpodautoscalers" ]
    verbs: [ "create", "get", "list", "watch", "update", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: model-deployments
subjects:
  - kind: ServiceAccount
    name: default
    namespace: model-deployments
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
