# frontend-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: your-dockerhub-username/frontend-ui:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service
spec:
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
