apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui-deployment
  namespace: model-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: frontend-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service
  namespace: model-deployments
spec:
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Specify a static NodePort (optional)
  type: NodePort
